import type {
  Memory,
  Comment,
  Diya,
  GalleryItem,
  StoryChapter,
  SiteSettings,
} from "./types";

const day = 24 * 60 * 60 * 1000;
const now = Date.now();

export const placeholderMemories: Memory[] = [
  {
    id: "m1",
    name: "Priya Sharma",
    relationship: "Niece",
    title: "The best storyteller",
    message:
      "Every Diwali, Rajesh uncle would gather all of us cousins and tell the same stories — and somehow they got funnier every year. His laugh filled the whole house. I can still hear it.",
    category: "Family",
    imageUrl: "https://picsum.photos/seed/rajesh-family/900/640",
    visibility: "public",
    status: "approved",
    hearts: 24,
    rememberCount: 11,
    createdAt: now - 2 * day,
  },
  {
    id: "m2",
    name: "Daniel Okafor",
    relationship: "Colleague & friend",
    title: "Quietly generous",
    message:
      "He never made a fuss about it, but Rajesh helped me through my first year at work — covering shifts, sharing lunch, never letting me feel alone. The kindest man I've known.",
    category: "Kindness",
    imageUrl: null,
    visibility: "public",
    status: "approved",
    hearts: 18,
    rememberCount: 7,
    createdAt: now - 5 * day,
  },
  {
    id: "m3",
    name: "Anita Patel",
    relationship: "Family friend",
    title: "Tea on the porch",
    message:
      "Sunday mornings meant chai on the porch with Rajesh and Meena. He'd put far too much sugar in mine and pretend he forgot. I'd give anything for one more cup.",
    category: "Family",
    imageUrl: "https://picsum.photos/seed/rajesh-chai/900/700",
    visibility: "public",
    status: "approved",
    hearts: 31,
    rememberCount: 14,
    createdAt: now - 9 * day,
  },
  {
    id: "m4",
    name: "Sam Whitfield",
    relationship: "Neighbour",
    title: "Always the first to help",
    message:
      "Flat tyre, locked-out front door, a ladder needed at 7am — Rajesh was already on his way before you finished asking. A proper good man.",
    category: "Kindness",
    imageUrl: null,
    visibility: "public",
    status: "approved",
    hearts: 12,
    rememberCount: 5,
    createdAt: now - 12 * day,
  },
  {
    id: "m5",
    name: "Leela Krishnan",
    relationship: "Old school friend",
    title: "The advice I still follow",
    message:
      "\"Be kind first, be right later.\" He said it to me at eighteen and I've carried it my whole life. Thank you, Rajesh.",
    category: "Advice",
    imageUrl: null,
    visibility: "public",
    status: "approved",
    hearts: 27,
    rememberCount: 9,
    createdAt: now - 16 * day,
  },
  // A pending one so the admin dashboard has something to moderate.
  {
    id: "m6",
    name: "Reuben Mensah",
    relationship: "Cricket club",
    title: "Sunday league legend",
    message:
      "He claimed he was 'just making up the numbers' and then took three wickets every single week. We'll miss you at the crease, skipper.",
    category: "Funny",
    imageUrl: "https://picsum.photos/seed/rajesh-cricket/900/620",
    visibility: "public",
    status: "pending",
    hearts: 0,
    rememberCount: 0,
    createdAt: now - 6 * 60 * 60 * 1000,
  },
];

export const placeholderComments: Comment[] = [
  {
    id: "c1",
    memoryId: "m1",
    name: "Vik",
    message: "I remember those nights so well. Thank you for writing this.",
    createdAt: now - 1 * day,
  },
  {
    id: "c2",
    memoryId: "m3",
    name: "Meena",
    message: "Too much sugar, every single time. I miss it too. ❤️",
    createdAt: now - 8 * day,
  },
];

export const placeholderDiyas: Diya[] = [
  { id: "d1", name: "Vik", message: "Keeping your light alive, Dad.", createdAt: now - 1 * day },
  { id: "d2", name: "Bhavik", message: "Miss you every day.", createdAt: now - 2 * day },
  { id: "d3", name: "Meena", message: "Forever my love.", createdAt: now - 3 * day },
  { id: "d4", name: "Priya", message: "Shine on, uncle.", createdAt: now - 4 * day },
  { id: "d5", name: "Daniel", message: "Thank you for everything.", createdAt: now - 5 * day },
  { id: "d6", name: "Anita", message: "Saving you a cup of chai.", createdAt: now - 6 * day },
  { id: "d7", name: "Leela", message: "Be kind first. Always.", createdAt: now - 7 * day },
];

export const placeholderSettings: SiteSettings = {
  name: "Rajesh's Light",
  subtitle: "A place to remember, honour, and celebrate the life of Rajesh.",
  intro:
    "Rajesh was a husband, father, brother, friend, and the heart of our family. This space is for everyone who loved him to share stories, photos, and memories so his light continues through all of us.",
  datesLabel: "1958 — 2025",
  heroImageUrl: null,
  storyIntro:
    "A few chapters from a life filled with love, laughter, and quiet kindness. Add your own photos and words to keep telling his story.",
};

export const placeholderStory: StoryChapter[] = [
  {
    id: "s1",
    year: "The beginning",
    title: "Early Life",
    text: "Rajesh grew up surrounded by warmth and laughter, the kind of childhood that shapes a gentle, generous heart. Even as a boy he had a way of making everyone around him feel they belonged.",
    imageUrl: null,
    order: 1,
    createdAt: now - 100 * day,
  },
  {
    id: "s2",
    year: "His own family",
    title: "Family",
    text: "When he built his own family, he poured everything into it. Sunday meals, long stories, and an open door for anyone who needed one — home was wherever Rajesh was.",
    imageUrl: null,
    order: 2,
    createdAt: now - 99 * day,
  },
  {
    id: "s3",
    year: "Being a dad",
    title: "Fatherhood",
    text: "To Vik and Bhavik, he was steady, patient, and endlessly proud. He taught by example: work hard, stay humble, and never let a chance to laugh together pass you by.",
    imageUrl: null,
    order: 3,
    createdAt: now - 98 * day,
  },
  {
    id: "s4",
    year: "What he stood for",
    title: "Work & Values",
    text: "He believed in doing things properly and treating everyone with respect. Colleagues remember a man who led quietly, helped freely, and always kept his word.",
    imageUrl: null,
    order: 4,
    createdAt: now - 97 * day,
  },
  {
    id: "s5",
    year: "Forever",
    title: "Moments We'll Always Remember",
    text: "The chai on the porch. The terrible-wonderful jokes. The way he made ordinary days feel like a gift. These are the moments that keep his light alive in all of us.",
    imageUrl: null,
    order: 5,
    createdAt: now - 96 * day,
  },
];

export const placeholderGallery: GalleryItem[] = [
  {
    id: "g1",
    imageUrl: "https://picsum.photos/seed/rajesh-1/800/1000",
    caption: "Family Diwali, the whole house together",
    category: "Family",
    uploadedBy: "Meena",
    createdAt: now - 3 * day,
    status: "approved",
  },
  {
    id: "g2",
    imageUrl: "https://picsum.photos/seed/rajesh-2/800/600",
    caption: "Dad and Vik on the pier",
    category: "Vik & Dad",
    uploadedBy: "Vik",
    createdAt: now - 4 * day,
    status: "approved",
  },
  {
    id: "g3",
    imageUrl: "https://picsum.photos/seed/rajesh-3/800/900",
    caption: "Goa, summer of '09",
    category: "Holidays",
    uploadedBy: "Bhavik",
    createdAt: now - 5 * day,
    status: "approved",
  },
  {
    id: "g4",
    imageUrl: "https://picsum.photos/seed/rajesh-4/800/700",
    caption: "Mum & Dad, anniversary dinner",
    category: "Mum & Dad",
    uploadedBy: "Vik",
    createdAt: now - 6 * day,
    status: "approved",
  },
  {
    id: "g5",
    imageUrl: "https://picsum.photos/seed/rajesh-5/800/1100",
    caption: "Dad and Bhavik building the shed",
    category: "Bhavik & Dad",
    uploadedBy: "Bhavik",
    createdAt: now - 7 * day,
    status: "approved",
  },
  {
    id: "g6",
    imageUrl: "https://picsum.photos/seed/rajesh-6/800/600",
    caption: "Beach day with the cousins",
    category: "Beach Day",
    uploadedBy: "Priya",
    createdAt: now - 8 * day,
    status: "approved",
  },
  {
    id: "g7",
    imageUrl: "https://picsum.photos/seed/rajesh-7/800/950",
    caption: "Old photo — Rajesh in his twenties",
    category: "Old Photos",
    uploadedBy: "Meena",
    createdAt: now - 9 * day,
    status: "approved",
  },
  {
    id: "g8",
    imageUrl: "https://picsum.photos/seed/rajesh-8/800/650",
    caption: "Sunday football with friends",
    category: "Friends",
    uploadedBy: "Daniel",
    createdAt: now - 10 * day,
    status: "approved",
  },
  {
    id: "g9",
    imageUrl: "https://picsum.photos/seed/rajesh-9/800/800",
    caption: "Garden in full bloom, his pride and joy",
    category: "Family",
    uploadedBy: "Meena",
    createdAt: now - 11 * day,
    status: "approved",
  },
  {
    id: "g10",
    imageUrl: "https://picsum.photos/seed/rajesh-10/800/1000",
    caption: "Holiday in the Lake District",
    category: "Holidays",
    uploadedBy: "Vik",
    createdAt: now - 12 * day,
    status: "approved",
  },
  {
    id: "g11",
    imageUrl: "https://picsum.photos/seed/rajesh-11/800/700",
    caption: "Friends' reunion, 2018",
    category: "Friends",
    uploadedBy: "Daniel",
    createdAt: now - 13 * day,
    status: "approved",
  },
  {
    id: "g12",
    imageUrl: "https://picsum.photos/seed/rajesh-12/800/900",
    caption: "Beach sunset, the family favourite",
    category: "Beach Day",
    uploadedBy: "Priya",
    createdAt: now - 14 * day,
    status: "approved",
  },
];
